version: "3"

services:
   web:
      build:
         context: .
         dockerfile: dev.Dockerfile
      container_name: turbo-enjeksiyon
      volumes:
         - ./src:/var/www/html
      ports:
         - "8086:80"
